apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmap.yml
  - secret.yml
  - mongo.yml
  - auth-service.yml
  - product-service.yml
  - gateway.yml
  - frontend.yml
  - ingress.yml

labels:
  - pairs:
      app.kubernetes.io/part-of: microshop
      app.kubernetes.io/managed-by: argocd
      environment: lab
    includeSelectors: false
    includeTemplates: true
