apiVersion: v1
kind: Secret
metadata:
  name: microshop-secret
  namespace: microshop
type: Opaque
stringData:
  AUTH_MONGO_URI: "mongodb://mongo:27017/microshop_auth"
  PRODUCT_MONGO_URI: "mongodb://mongo:27017/microshop_product"
